stages:
  - test

phpunit:
  stage: test
  image: composer:2
  cache:
    key: composer-${CI_COMMIT_REF_SLUG}
    paths:
      - .composer-cache/
  variables:
    COMPOSER_CACHE_DIR: "$CI_PROJECT_DIR/.composer-cache"
  script:
    - composer validate --strict
    - composer install --no-interaction --no-progress --prefer-dist
    - composer cs:check
    - composer analyse
    - composer test
